# 情報システム概論　第5回

## ニューラルネットワークの学習

### データから学習する
学習とは訓練データから最適な重みパラメータの値を自動で獲得すること．  
**重みを手作業で設定しないといけないと大変！**

> 前回は適当な重みを設定しましたけど，適当だとニューラルネットワークは何もできません．例えば前回の最後にやった数字の画像を分類するためには，ニューラルネットワークの重みをどのようにすればよいのか，などを訓練データから自動で獲得するための手法を学びます．

### データ駆動
これまでの機械学習
- 人が特徴量を設計する

ニューラルネットワーク
- データ(今回は画像)に含まれる重要な特徴量についても機械が学習する
    - 数字の認識，猫の認識，人の顔の認識それぞれに対して基本的な仕組みは同じ
    - 与えられたデータを学習して，与えられた問題のパターンを発見する
    - end-to-end machine learning であると言われる

<img alt="datadriven.png" width="600" src="http://drive.google.com/uc?export=view&id=1deRUN-joBsxwI-41EbZRC29jVNybJKok">

> Lesson1で上記のような，花の画像認識を例に説明しましたよね．これまでの機械学習の研究では，花びらの数，花びらの形，色などの特徴を使えばうまく花の分類ができるんじゃないか．．．ということを人が考えていました．ニューラルネットワークは共通の仕組み(データに重みを掛け算して，バイアスを足して，活性化関数に入れるという仕組み) で，データの中からパターンを発見することで，人が何に注目すれば分類できるか等を教えなくても，自動で目的の仕事 (花の分類や，猫/犬の分類など) をできるようになります．今回は数字の画像の分類ができるように，学習する仕組みを作ってみましょう．

### 訓練データとテストデータ
- 訓練データ：学習を行うためのデータ
- テストデータ：学習した結果のモデルの実力を評価するためのデータ

**訓練データとテストデータをなぜ分けるのか？**  
汎化能力を評価したい．まだ見ぬデータに対する能力を測る必要がある．  
例えば，数字の認識の場合，訓練データの数字を書いた人の数字のクセに特化した学習をすると良くない．  
訓練データで評価するとこのような状態に気づけない．

ちなみに，あるデータセットにだけ過度に対応した状態を過学習 (overfitting) という．

> 訓練データは「過去問」，テストデータは「本番の新しい問題」に相当します．過去問で身に着けた力を，過去問を使って測っても公平な評価はできない可能性があります．正しく中身を理解していればよいですが，例えば「(A)という選択肢が3問連続で正解になることはない」といった本質とずれた側面を学習しているだけのこともあるからです．これが過去問に過学習してしまった状態というわけです．能力を正確に測るには「本番の新しい問題」にチャレンジする必要があります．

## 損失関数
ニューラルネットワークの学習の際，「一つの指標」によって現在のニューラルネットワークの状態を表す．
この「一つの指標」を手がかりに最適なパラメータを探索する．このニューラルネットワークの学習で用いられる「一つの指標」が損失関数 (loss function) である．

損失関数はニューラルネットワークの性能の”悪さ”を示す指標であり，ニューラルネットワークがどれだけ学習データに適合していないかを表す．

> 良さじゃなくて悪さなんですね．
> この悪さを表す指標である損失関数の値 (損失スコア)が小さくなるように少しずつ重みやバイアスを調整してやると，ニューラルネットは訓練データによく適合するようになる (「数字の画像」と「答え」のペアをたくさん入れてあげると，「数字の画像」に対する「答え」が出るようになる) んですね．これは，Lesson1の下記のスライドで説明しましたね．

<img alt="neuralnet1.png" width="600" src="http://drive.google.com/uc?export=view&id=1ZbfQ_F5lBHmcsrRrqXFpgXuJQ8d0BPep">
<img alt="neuralnet2.png" width="600" src="http://drive.google.com/uc?export=view&id=1x_B-W4tDFHbpNpDiMLUDkQyt_JdEUKs6">
<img alt="neuralnet3.png" width="600" src="http://drive.google.com/uc?export=view&id=1RQpqVnufXh9J3PDkz_uEj8zLJgqYYm6c">


ここではよく使われる2つの損失関数を作ってみる．
- 2乗和誤差
- 交差エントロピー誤差

> まずは「悪さ」を数値にする関数である損失関数を作りましょう．

### 2乗和誤差
2乗和誤差 (mean squared error) は次の式で表される．

$$
E=\frac{1}{2}\sum_k(y_k - t_k)^2
$$

y_kはニューラルネットワークの出力ベクトル第k成分，t_kは教師データのベクトル第k成分を表す．
以下に例を示す．

In [ ]:
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0] # one-hot表現

> これはニューラルネットの出力は2が正解と言っていて，実際の答えも2だった場合です．この場合は損失関数の値は小さくなってほしいんですね．

2乗誤差を以下のように実装する．

In [ ]:
import numpy as np

def mean_squared_error(y, t):
    return 0.5 * np.sum((y - t) ** 2)

> これは上の式をそのままプログラムにしていますね．```**2```は2乗ということです．
yとtは複数の値を含む配列ですから，配列の各値の差を取って，それを2乗して，合計して，0.5を掛けています．

In [ ]:
mean_squared_error(np.array(y), np.array(t))

np.float64(0.09750000000000003)

> まあまあ小さいな値になっていますね．一方，下記のようにニューラルネットの出力を間違ってみると，2乗和誤差は大きくなりますね．
これで，損失関数の役割を果たしていることがわかります．

In [ ]:
y2 = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.5, 0.0]
mean_squared_error(np.array(y2), np.array(t))

np.float64(0.7225)

### 交差エントロピー誤差
交差エントロピー誤差 (cross entropy error) は次の式で表される．

$$
E=-\sum_k t_k \log y_k
$$


t_kはone-hot表現なので，結局正解ラベルが1に対応する出力の自然対数を計算するだけになる．

以下のように実装する．

In [ ]:
def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

```np.log(0)```になると，マイナス無限大になるので，そうならないように微小な値として ```delta = 1e-7``` を追加している．

> これも上の式をほぼそのままプログラムにしています．```np.log(y + delta)```のところだけ違いますが，上の説明のとおりです．  
> tはone-hot表現 ([0,1,0,0,0,0,0,0,0,0]など) のなので，正解のところだけが1になって，ほかは0なんです．だから，Σで合計をとっていますが，```t * np.log(y + delta)```はtが1のところだけ```np.log(y + delta)```になりますが，ほかは全部0になるんですね．なので，実質正解の部分だけ```-t * np.log(y + delta)```の計算をしていることになります．  
では，本当にこの計算で損失関数の役割を果たすのか確認してみましょう．

In [ ]:
cross_entropy_error(np.array(y), np.array(t))

np.float64(0.510825457099338)

In [ ]:
cross_entropy_error(np.array(y2), np.array(t))

np.float64(2.302584092994546)

> はい．上記のように，ニューラルネットの出力が正解の場合は値が小さくなって，不正解の場合は値が大きくなっていますね．  
これで，交差エントロピー誤差も損失関数の役割を果たすことがわかります．

### ミニバッチ学習

たくさんある学習データに対する損失関数を計算する必要があるが，何千個何万個もあるようなデータの場合，学習に時間がかかってしまう．
そこで，
- データの中から一部を選び出す
    - 通常はランダムに特定の数を選び出す
- その一部のデータ (ミニバッチ) を全体の「近似」と考える
- ミニバッチごとに学習を行う (ミニバッチ学習)

MNISTデータセットからランダムに一部を取り出す機能を以下のように実装する．

In [ ]:
from google.colab import drive
import sys

drive.mount('/content/drive')
save_dir = '/content/drive/MyDrive/data'
!ls ./drive/MyDrive/data/ | grep .pkl

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
mnist_X.pkl
mnist_y.pkl
sample_weight.pkl


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
import pickle
import os

with open(os.path.join(save_dir, 'mnist_X.pkl'), 'rb') as f:
  X = pickle.load(f)
with open(os.path.join(save_dir, 'mnist_y.pkl'), 'rb') as f:
  y = pickle.load(f)

x_train, x_test, t_train, t_test = train_test_split(X, y, test_size=10000, random_state=42)
t_train = np.eye(10)[t_train]   # 単位行列（対角成分が1の行列）を作成し，インデックスを指定
t_test = np.eye(10)[t_test]   # 単位行列（対角成分が1の行列）を作成し，インデックスを指定

> これは前回のLesson4でもありましたね．MNISTのデータを取得しています．
> t_train, t_testにはもともと正解ラベルが格納されていますが，これをone-hot表現に変換しています

In [ ]:
print(x_train.shape)
print(t_train.shape)

(60000, 784)
(60000, 10)


In [ ]:
train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)  # すべてのデータのサイズからbatch_sizeだけランダムに数字を選ぶ
print(batch_mask)

x_batch = x_train[batch_mask]
t_batch = t_train[batch_mask]

[29888 41535 33953 46952 26074 10360 27005  2915 26271  3781]


> ```train_size = x_train.shape[0]```で訓練画像の枚数を取得しています．

In [ ]:
train_size

60000

> 訓練用の画像が6万枚ありますね．この6万枚の中から```batch_mask = np.random.choice(train_size, batch_size) ```で10枚ランダムに画像の番号を選択して，その下で実際に選択された画像とラベルを取得しているんですね．実際に何が取れているか見てみましょう．

In [ ]:
x_batch

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
t_batch

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

> ```x_batch```は画像で，0～1の間の値になるので，上記のように中身を表示してみると0.というふうに省略されて表示されてしまいますが，```t_batch```の方はone-hot表現なので，正解を表す1と0の並びが見えますね．  
こういうふうに，ある程度の量のミニバッチごとに損失関数を一気に計算すると，効率よく学習できます．

これで，ミニバッチを取り出すことができた．先程作った交差エントロピー誤差を改良することで，ミニバッチを
まとめて損失関数の計算ができるように実装する．

In [ ]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)

    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size

> 上記は ``` -np.sum(t * np.log(y + 1e-7)) / batch_size``` でミニバッチの数で割っていますので，平均を出していますね．ミニバッチの数が10でも100でも同じような値になるようにしています．  
また，
```
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
```
としているのは，ミニバッチじゃなくて1個だけ計算する場合に，2個以上の場合と行列の形が同じになるようにしているんですね．  
上でt_batchの中身をみましたが，下記のような感じでしたよね．
```
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])
```
これは，かっこの中にかっこが入っている形になっています．一方，1個だけ計算する場合はかっこは1重になりますので，
そういう場合でも，かっこを2重にしているんですね．  
下記のように，かっこが1重の場合でも，計算できることがわかります．もちろん，ミニバッチでいっぺんにたくさん計算することもできます．

In [ ]:
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0] # one-hot表現
cross_entropy_error(np.array(y), np.array(t))

np.float64(0.510825457099338)

### 損失関数が小さくなる重みを探す

上記で作った損失関数が小さくなる重みを探すことがニューラルネットワークの学習である．
ただ，重みはたくさんあり，闇雲に探すと大変なので，勾配法を用いる．

重みが1つの場合で簡単に説明する．

<img alt="gradient.png" width="600" src="http://drive.google.com/uc?export=view&id=1hkZFJhVGZONhRoXnxo5yBSmpmR5bwoVY">

> 縦軸が損失関数で，横軸はある1つの重みですね．実際は重みはたくさんありますけど，簡単に考えるために1つにしています．
①は重みを変えると，損失関数がこのように変化するということを表しています．
最初は重みはでたらめな値になっていますので，②の状態ですね．損失関数の値は結構高くなっています．それで，
③この時の傾きを計算 (微分) するんですね．そうすると，この例ですとマイナスの大きな傾きになります．なので，重みを
マイナスとは逆のプラス方向に大きくずらします．そうすると，重みは④の点に移動して，そこで再度傾きを計算します．
そうすると，今度はまだマイナスですけど，前よりは傾きが緩やかになっていますね．なので，さっきと同じように
プラス方向に重みをずらすんですけど，今度は傾きが緩やかなので，少しだけずらします．これを何度も繰り返すと
最後には傾きが0になるところまで到着します．傾きが0のところは損失関数が小さくなっていますね．なので，
ここが重みの値としていいんじゃないか，となります．

実際には，重みはたくさんあるので，偏微分により，すべての重みに対する微分を行う．
このようにして，すべての重みに対して，どっち方向にどれくらいずらせばよいかを算出できる．
以下のように，すべての変数の偏微分をベクトルとしてまとめたものを勾配 (gradient) と言う．

$$
\left(\frac{\partial f}{\partial w_0}, \frac{\partial f}{\partial w_1}, \frac{\partial f}{\partial w_2}, \cdots\right)
$$

> 上記のfは損失関数ですね．たくさんの種類の重みがありますから，w0，w1・・・というふうに表しています．
それで，fを各wで偏微分するんですね．そうすると，上記のようにあらわされて，それぞれの重みをどっち(プラス？マイナス？) 方向に
どれくらいずらせばいいかわかります．


### 微分
では，微分するためのプログラムはどのように作ればよいのだろうか？

微分は以下の数式で定義される．

$$
\frac{\mathrm{d}f(x)}{\mathrm{d}x}=\lim_{h\rightarrow 0}\frac{f(x+h)-f(x)}{h}
$$

xの「小さな変化」によって，関数f(x)の値がどれだけ変化するか，ということを意味する．

このときの「小さは変化」であるhを，限りなく0に近づけているので，プログラムでは，
hに小さな値を代入して，計算すれば良い．

ただ，誤差が出るので，誤差を少しでも減らす工夫として，(x + h) と (x - h) での関数fの差分を計算することにする．

<img alt="diff_graph.png" width="600" src="http://drive.google.com/uc?export=view&id=1tj0jetDU207e4FPygP8HQ2ge_VOZaxHR">

> 左のようにf(x+h)-f(x)とする微分の計算では，本当の傾きと計算による傾きに誤差が生じますよね．一方，右のようにf(x+h)-f(x-h)だと誤差は小さくなりますね．

それでは，微分を以下のように実装する．  
※ このような微分の求め方を数値微分と呼び，数式の展開によって微分を求めることは，「解析的」という言葉を用いて表す．

In [ ]:
def numerical_diff(f, x):
    h = 1e-4 # 0.0001
    return (f(x+h) - f(x-h)) / (2*h)

> 上記は微分の計算を素直にプログラムにしていますね．

実際に微分できるか，y=0.01x^2 + 0.1x を微分して試してみる．

In [ ]:
def function_1(x):
    return 0.01*x**2 + 0.1*x

In [ ]:
numerical_diff(function_1, 5)

0.1999999999990898

In [ ]:
numerical_diff(function_1, 10)

0.2999999999986347

真の微分はそれぞれ0.2, 0.3となり，数値微分の結果とは厳密には一致しないが，その誤差は非常に小さいことがわかる．

### 偏微分
重みはたくさんあるので，それぞれに対して偏微分を行って，勾配を求める必要がある．
それでは，偏微分して勾配を求めるためのプログラムはどのように作るか？

まず，以下を偏微分してみよう．

$$
f(x_0,x_1)=x_0^2+x_1^2
$$

これをプログラムで書くと，

In [ ]:
def function_2(x):
    return x[0]**2 + x[1]**2

とかけるが，先程の微分の関数を使って，偏微分をするときは少し面倒になる．

x0 = 3, x1 = 4 のときの x0 に対する偏微分を求めてみる．

In [ ]:
def function_2_1(x0):
    return function_2(np.array([x0, 4.0]))

numerical_diff(function_2_1, 3.0)

np.float64(6.00000000000378)

次に，x0 = 3, x1 = 4 のときの x1 に対する偏微分を求めてみる．

In [ ]:
def function_2_2(x1):
    return function_2(np.array([3.0, x1]))

numerical_diff(function_2_2, 4.0)

np.float64(7.999999999999119)

このように，偏微分ではターゲットとする変数以外は，ある値に固定して，ターゲットの変数で微分すれば良い．ただ，ちょっとめんどくさいので，以下のようにして，一気にすべての変数に対して偏微分を求め，勾配を算出できるようにする．

In [ ]:
def _numerical_gradient_no_batch(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x) # xと同じ形状の配列を生成

    for idx in range(x.size):
        tmp_val = x[idx] # ターゲットとする変数を退避しておく

        # f(x+h)の計算
        x[idx] = tmp_val + h
        fxh1 = f(x)

        # f(x-h)の計算
        x[idx] = tmp_val - h
        fxh2 = f(x)

        grad[idx] = (fxh1 - fxh2) / (2*h)

        x[idx] = tmp_val # 退避しておいた値でもとの値に戻す

    return grad

> 上記のプログラムは割と複雑ですよね．  
```x =  np.array([3.0, 4.0])```で fが
```
def function_2(x):
    return x[0]**2 + x[1]**2
```
の時の動作を見ていきましょうか．

In [ ]:
x =  np.array([3.0, 4.0])
grad = np.zeros_like(x)
grad

array([0., 0.])

> 上記のように，まずgradはxと同じサイズの配列で全部0が入るんですね．そのあとの```for idx in range(x.size):```についてですが，今回は```x.size```が2ですから，```range(x.size)```は```[0,1]```と同じ意味合いになります．ここでのfor文はこの配列から1個取り出して，idxに入れて，その下の処理をやって，処理が終わったら，配列の次の1つを取り出して，同じ処理をやるんですね．

> で，forで2回繰り返す処理の1回目の内容ですが，  
まず，```tmp_val = x[idx]``` はforの1回目では，idxが0ですから，tmp_valには```x[0]```である3.0が入りますね．これは，この下の処理のために，いったん``` x[idx]```をtmp_valに退避しておく意味があります．

> 次は下記の部分ですが，
```
        x[idx] = tmp_val + h
        fxh1 = f(x)
```
idxが0ですからx[0]にtmp_val + hを入れていますね．なので，xは[3.0001, 4.0]になりますよね．これをf(x)に代入して計算した結果をfxh1に入れるんですね．

> あとは，その下は ```tmp_val - h```のところが違いますが同じことをやっています．xは[2.9999, 4.0]になって，これをf(x)に代入して計算した結果をfxh2に入れているんですね．

> 最後に ```grad[idx] = (fxh1 - fxh2) / (2*h)```でこれは結局x0に対する偏微分の計算になっていて，その結果をgrad[0]に入れています．そして，```x[idx] = tmp_val```でxを元にもどします．

> で，for文ですから，次はidxを1にして，同じように今度はx1に対する偏微分の計算をして，今度はgrad[1]に入れます．こうするとfor文を終えるころには，gradにはそれぞれの値での偏微分の結果が入っていることになります．

> 実際にx0, x1での偏微分の計算をしてみましょう．

In [ ]:
_numerical_gradient_no_batch(function_2, np.array([3.0, 4.0]))

array([6., 8.])

> 上記のように，一気に偏微分ができるようになりました．これで，勾配を一気に計算できますね．

### 勾配法

以上のようにして，関数の勾配を求められるようになった．
あとは，勾配が示す方向に重みを繰り返し変化させればよい．
このように，勾配方向へ進むことを繰り返すことで，関数の値を徐々にへらすのが勾配法 (gradient method) である．

勾配法は以下の式で表す (変数が２つの場合)．

$$
x^{(t+1)}_0= x^{(t)}_0 - \eta\frac{\partial f\left(x^{(t)}_0,x^{(t)}_1\right)}{\partial x_0}\\
x^{(t+1)}_1= x^{(t)}_1 - \eta\frac{\partial f\left(x^{(t)}_0,x^{(t)}_1\right)}{\partial x_1}
$$

η (イータ) は更新の量を表し，学習率 (learning rate) と呼ぶ．
上の式を何度も繰り返すことで，徐々に関数の値を減らしていく．

> これは，上の①～④の処理を式にしているだけですね．傾きとは逆 (マイナスを掛ける) にxを何度も動かすということですね．この時にどれくらい大きく動かすかを，ηをつかって調節できるようにしています．

なお，最小値を探す場合を勾配降下法，最大値を探す場合を勾配上昇法と呼ぶ．

勾配降下法を以下のように実装する．

In [ ]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x

    for i in range(step_num):
        grad =_numerical_gradient_no_batch(f, x)
        x -= lr * grad

    return x

> このプログラムはstep_numの回数だけ，forの処理を繰り返して，xの値を動かします．step_numは何も設定しない場合は100回となります．また，学習率ηはlrで調整しますが，何も設定しない場合は0.01となります．fは小さくする対象の関数で，init_xは最初のxの位置ですね．

> forの中の処理はまず偏微分を計算して，計算結果に学習率をかけて，xから引いています．これで，fが小さくなる方向にx動かしているんですね．今まで学んできたことをプログラムにしているだけですね．

> では実際に関数の値が小さくなるxを見つけられるかやってみましょう．```init_x = np.array([-3.0, 4.0])```で設定する値は，なんでもよいです．

In [ ]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])

勾配法をつかって，$f(x_0,x_1)=x^2_0 + x^2_1$の最小値を探索した．
真の最小値は (0, 0) なので，勾配法によって，ほぼ正しい結果を得ることができた．

さて，ここで学習率を変えてみる．

In [ ]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=10.0, step_num=100)

array([-2.58983747e+13, -1.29524862e+12])

In [ ]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=1e-10, step_num=100)

array([-2.99999994,  3.99999992])

学習率が大きすぎると，大きな値へと発散し，逆に，学習率が小さすぎると，殆ど更新されずに終わってしまう．

> 学習率は大きすぎても，小さすぎてもダメなんですが，どんな値がいい値なのかはわかりませんので，実際にやりながらうまくいく値を探っていくことになります．

### 学習アルゴリズムを作る

これで，ニューラルネットワークの学習に関する部品は出揃った．
- 損失関数
- ミニバッチ
- 勾配
- 勾配降下法

以下のような方針でニューラルネットワークの学習アルゴリズムを組み立てる．

- 前提
    - ニューラルネットワークには重みとバイアスがあり，この重みとバイアスを訓練データに適応するように調整したい！
    - これを学習とよび，以下の4つの手順で行う．


- ステップ1 (ミニバッチ)
    - 訓練データの中からランダムに一部のデータを選び出す．
- ステップ2 (勾配の算出)
    - ミニバッチの損失関数の値をへらすために，各重みパラメータの勾配を求める．
- ステップ3 (パラメータの更新)
    - 重みパラメータを勾配方向に微小量だけ更新する．
    - 今回はミニバッチとして無作為に選ばれたデータを使用することから，確率的勾配降下法 (stochastic gradient descent SGD) と呼ぶ．
- ステップ4 (繰り返す)
    - ステップ1～3を繰り返す．
    
まずは，以前作った活性化関数を改めて作る (これらは前に一度作りましたので，コピペしてもらって問題ありません)．


In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) # オーバーフロー対策
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

次に，バッチ学習対応版の勾配を計算する関数を実装する．

> バッチ対応の 交差エントロピー誤差 を作りましたが，それと同じようなアイディアです．1個だけの場合は，すでに作っている，```_numerical_gradient_no_batch(f, X)```の結果を返します．そうじゃなくて，バッチでたくさん入力される場合は，```_numerical_gradient_no_batch(f, x)```をバッチの数だけ繰り返します．

In [ ]:
def numerical_gradient(f, X):
    if X.ndim == 1:
        return _numerical_gradient_no_batch(f, X)
    else:
        grad = np.zeros_like(X)

        for idx, x in enumerate(X):
            grad[idx] = _numerical_gradient_no_batch(f, x)

        return grad

さらに，今回学習する2層のニューラルネットワークを一つのクラスとして実装する．

> クラスについてはPython入門でやりましたけど，関数と値を持つことができるんでしたよね．学習するときは何度も重みをずらしますから，前の重みを覚えておいて，それを勾配に従ってずらして，ずらした結果の重みを覚えておいて，さらにずらして・・・ということをします．この時に値をもっておくことができると便利なんです．


In [48]:
class TwoLayerNet:

    def __init__(self, input_size, hidden_size, output_size, weight_init_std=0.01):
        # 重みの初期化
        self.params = {}
        self.params['W1'] = weight_init_std * np.random.randn(input_size, hidden_size)
        self.params['b1'] = np.zeros(hidden_size)
        self.params['W2'] = weight_init_std * np.random.randn(hidden_size, output_size)
        self.params['b2'] = np.zeros(output_size)

    def predict(self, x):
        W1, W2 = self.params['W1'], self.params['W2']
        b1, b2 = self.params['b1'], self.params['b2']

        a1 = np.dot(x, W1) + b1
        z1 = sigmoid(a1)
        a2 = np.dot(z1, W2) + b2
        y = softmax(a2)

        return y

    # x:入力データ, t:教師データ
    def loss(self, x, t):
        y = self.predict(x)

        return cross_entropy_error(y, t)

    def accuracy(self, x, t):
        y = self.predict(x)
        y = np.argmax(y, axis=1)
        t = np.argmax(t, axis=1)

        accuracy = np.sum(y == t) / float(x.shape[0])
        return accuracy

    # x:入力データ, t:教師データ
    def numerical_gradient(self, x, t):
        loss_W = lambda W: self.loss(x, t)

        grads = {}
        grads['W1'] = numerical_gradient(loss_W, self.params['W1'])
        grads['b1'] = numerical_gradient(loss_W, self.params['b1'])
        grads['W2'] = numerical_gradient(loss_W, self.params['W2'])
        grads['b2'] = numerical_gradient(loss_W, self.params['b2'])

        return grads


> 結構たくさん書かないといけなくて，内容の理解は大変かもしれないですが，説明しますね．

> ```def __init__(self, input_size, hidden_size, output_size, weight_init_std=0.01): ```はクラスを使うときに，最初に実行されます．引数としては
* input_size: 入力層のニューロンの数
* hidden_size: 中間層のニューロンの数
* output_size: 出力層のニューロンの数
* weight_init_std: 最初の重みをどれくらい小さい値にするか

>ここではニューラルネットワークに最初の重みとして，```self.params['W1'] = weight_init_std * np.random.randn(input_size, hidden_size)```という風にランダムな値を設定して，最初のバイアスとして，```self.params['b1'] = np.zeros(hidden_size)```という風に0を設定しています．  
```    def predict(self, x):```は前回のLesson4でやりましたよね．推論の処理をしています．  
```    def loss(self, x, t):```は損失関数の計算をしています．推論した結果がどれくらい悪いか (正解から外れているか) を計算するために，交差エントロピー誤差を計算しています．  
```    def accuracy(self, x, t):```はなくてもいいんですけど，正解率を計算しています．100個のうち50個正解すれば0.5という風に正解率を出力します．  
```    def numerical_gradient(self, x, t):```で損失関数を小さくするために，重みとバイアスを動かす方向を示す勾配を求めます．
難しい書き方ですが，```loss_W = lambda W: self.loss(x, t)```で小さくする対象の関数である損失関数```def loss(self, x, t):```を``` loss_W```という名前にしています．そして，``` numerical_gradient(loss_W, self.params['W1'])```でW1に含まれるたくさんのWの値を少し動かすことでそれぞれのWに対する偏微分を行い，勾配を計算して，grads['W1']に入れています．ほかの重みやバイアスの勾配の計算も同じようにやっています．  
結構たくさん書かないといけないので，大変かもしれませんが，やっていることはこれまで習ったことを整理して書き直している感じです．

最後に，ミニバッチ学習をするプログラムを実装する．  

In [49]:
import numpy as np
from sklearn.model_selection import train_test_split
import pickle
import os

with open(os.path.join(save_dir, 'mnist_X.pkl'), 'rb') as f:
  X = pickle.load(f)
with open(os.path.join(save_dir, 'mnist_y.pkl'), 'rb') as f:
  y = pickle.load(f)

x_train, x_test, t_train, t_test = train_test_split(X, y, test_size=10000, random_state=42)
t_train = np.eye(10)[t_train]   # 単位行列（対角成分が1の行列）を作成し，インデックスを指定
t_test = np.eye(10)[t_test]   # 単位行列（対角成分が1の行列）を作成し，インデックスを指定

In [50]:
network = TwoLayerNet(input_size=784, hidden_size=50, output_size=10)

iters_num = 10000  # 繰り返しの回数を適宜設定する
train_size = x_train.shape[0]
batch_size = 100
learning_rate = 0.1

train_loss_list = []
iter_per_epoch = max(train_size / batch_size, 1)

for i in range(iters_num):
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]

    # 勾配の計算
    grad = network.numerical_gradient(x_batch, t_batch)

    # パラメータの更新
    for key in ('W1', 'b1', 'W2', 'b2'):
        network.params[key] -= learning_rate * grad[key]

    loss = network.loss(x_batch, t_batch)
    train_loss_list.append(loss)
    # print(loss)

    if i % iter_per_epoch == 0:
        train_acc = network.accuracy(x_train, t_train)
        test_acc = network.accuracy(x_test, t_test)
        print("train acc, test acc | " + str(train_acc) + ", " + str(test_acc))

train acc, test acc | 0.0987, 0.1036


KeyboardInterrupt: 

> 上記プログラムは実行時間がかなりかかるので，途中で止めたためエラーになっています．これは誤りではないので，気にしないでください．  
> みなさんも，ある程度学習したら，■ボタンを押して学習を止めていただいて構いません．

> 中身の説明をします．このプログラムはTwoLayerNetのクラスを使って，数字の画像の分類をするための学習をします．  
```network = TwoLayerNet(input_size=784, hidden_size=50, output_size=10)```でTwoLayerNetのクラスのインスタンスを作って，クラスを使えるようにしています．Python入門でやりましたよね．この時に```__init__```が実行されますので，ニューラルネットの重みがランダムな値になって，バイアスが0になります．また，入力層として784個のニューロンとなっていますが，これは画像が784個の画素から構成されるためです．また，数字の画像を10種類に分類しますので，出力層は10個のニューロンになります．これらは前回最後にやりましたね．中間層は50個のニューロンになっていますが，これはとりあえず50にしているということで，50じゃなくても動きます．本来は中間層のニューロンの数をいろいろ変えて，どの数にするとうまく分類できるか，調整する必要があります．
```
iters_num = 10000  
train_size = x_train.shape[0]
batch_size = 100
learning_rate = 0.1
```
>ここは学習の繰り返し回数，訓練データの数 (6万枚でしたね)，ミニバッチのサイズ，学習率を設定しています．
```
train_loss_list = []
iter_per_epoch = max(train_size / batch_size, 1)
```
>ここは無視していただいて結構です．学習中の精度を表示するための記述です．  
```
for i in range(iters_num):
```
>ここは学習の繰り返し数だけ，繰り返すということですね．
```
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]
```
>ここはミニバッチとして，ランダムに訓練用の画像と，ラベル(正解) を100個ずつ取り出しているんですね．
```
    grad = network.numerical_gradient(x_batch, t_batch)
```
>で勾配の計算をして，
```
    for key in ('W1', 'b1', 'W2', 'b2'):
        network.params[key] -= learning_rate * grad[key]
```
>計算した勾配に学習率を掛けて，重みやバイアスから引いています (a -= b という書き方は a = a -b と同じ意味です)．これによって，重み，バイアスが損失関数が小さくなる方向に動かすことができます．  
以降の
```
    loss = network.loss(x_batch, t_batch)
    train_loss_list.append(loss)
    print(loss)
    if i % iter_per_epoch == 0:
        train_acc = network.accuracy(x_train, t_train)
        test_acc = network.accuracy(x_test, t_test)
        print("train acc, test acc | " + str(train_acc) + ", " + str(test_acc))
```
>は無視していただいて結構です．学習中の損失関数の値や精度を表示しています．

このプログラムを実行すると，時間はかかるが，少しずつ学習が行われる．学習の様子は，損失関数の値が少しずつ表示されて，その値がだんだん小さくなることでわかる．

> 今回はここまでです．以下は学習を止めたあとに，どれくらいの精度になっているか，を確認するプログラム ```network.accuracy(x_test, t_test)```と，実際に数字の画像を分類してみるプログラムです．```np.argmax(network.predict(x_test[20]))```で20番目の画像が何かを推定しています．```np.argmax(t_test[20])```で正解が何かを確認しています．


In [51]:
network.accuracy(x_test, t_test)

np.float64(0.1036)

In [52]:
np.argmax(network.predict(x_test[20]))

np.int64(9)

In [53]:
np.argmax(t_test[20])

np.int64(0)